//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kargo_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kargo()
        {
            this.Kargo_Durum = new HashSet<Kargo_Durum>();
            this.Sube = new HashSet<Sube>();
        }
    
        public int Kargo_id { get; set; }
        public int Takip_no { get; set; }
        public int Agirlik { get; set; }
        public string Tur { get; set; }
        public int Hacim { get; set; }
        public int Gonderici_id { get; set; }
        public int Alici_id { get; set; }
        public string Kargo_adres { get; set; }
        public double Ucret { get; set; }
        public string Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kargo_Durum> Kargo_Durum { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual Musteri Musteri1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sube> Sube { get; set; }
    }
}
