//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kargo_Takip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KargoDBEntities1 : DbContext
    {
        public KargoDBEntities1()
            : base("name=KargoDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kargo> Kargo { get; set; }
        public virtual DbSet<Kargo_Durum> Kargo_Durum { get; set; }
        public virtual DbSet<Kurye> Kurye { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<Sube> Sube { get; set; }
        public virtual DbSet<Sube_Calisani> Sube_Calisani { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
