//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kargo_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sube
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sube()
        {
            this.Kurye = new HashSet<Kurye>();
        }
    
        public int Sube_id { get; set; }
        public int Sube_Kargo_id { get; set; }
        public int Sube_tel_no { get; set; }
        public string Sube_adres { get; set; }
        public string Sube_adi { get; set; }
        public int Sube_calisani_id { get; set; }
    
        public virtual Kargo Kargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kurye> Kurye { get; set; }
        public virtual Sube_Calisani Sube_Calisani { get; set; }
    }
}
