//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kargo_Takip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sube_Calisani
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sube_Calisani()
        {
            this.Sube = new HashSet<Sube>();
        }
    
        public int Sube_calisani_id { get; set; }
        public int Sube_calisani_sifre { get; set; }
        public string Sube_calisani_tcno { get; set; }
        public string Sube_calisani_ad { get; set; }
        public string Sube_calisani_soyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sube> Sube { get; set; }
    }
}
